name: workflow with action 

on: push 

env: 
  ARTIFACT_VARIABLE: ${{ secrets.env_variable }}

jobs:
  job-1:
    name: Create an Artifact
    runs-on: ubuntu-latest
    steps:
      - name: checkout action 
        uses: actions/checkout@v4.2.2
      - name: upload atrtifact action 
        uses: actions/upload-artifact@v4.6.2
        with: 
          name: $ARTIFACT_VARIABLE
          path: ./hello-world.txt
